server:
  port: 8080
  mode: development

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: payment_service
    sslmode: disable

  mongodb:
    uri: mongodb://localhost:27017
    database: payment_service

jwt:
  secret: your-256-bit-secret
  access_token_expiration: 1h
  refresh_token_expiration: 168h # 7 days

payment:
  stripe:
    secretKey: your-stripe-secret-key
    webhookSecret: your-stripe-webhook-secret
  
  paypal:
    clientID: your-paypal-client-id
    secretKey: your-paypal-secret-key
    mode: sandbox # or production

rabbitmq:
  url: amqp://guest:guest@localhost:5672/

grpc:
  port: 50051

monitoring:
  prometheus:
    port: 9090
  grafana:
    port: 3000
